name: Update exchange rates
on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  run:
    name: Update with latest exchange rates
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4

      - name: Install dependencies
        run: npm install

      - name: Update source code
        env:
          EXCHANGERATESAPI_KEY: ${{ secrets.EXCHANGERATESAPI_KEY }}
        run: npm run rates:update

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          message: "Update exchange rates"
          default_author: github_actions
